# fly.toml app configuration file generated for restime on 2024-01-11T14:08:54+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restime"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[build]

[env]
  MAIL_USERNAME = "15camprestime@gmail.com"
  DOMAIN_NAME = "https://restime.fly.dev"
  ECPAY_MERCHANT_ID = "3002607"
  ECPAY_HASH_KEY = "pwFHCqoQZGmho4w6"
  ECPAY_HASH_IV = "EkRm7iFT261dpevs"

[deploy]
  release_command = "./bin/rails db:prepare"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]


[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
